language: c

sudo: true

os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tcl-tk; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-7 g++-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y tcl8.6-dev; fi
  
script:
  - autoreconf -vi
  - TCL_PREFIX=/usr/lib
  - INSTALL_PREFIX=/usr
  - if [ -f /usr/local/opt/tcl-tk/lib/tclConfig.sh ]; then TCL_PREFIX=/usr/local/opt/tcl-tk/lib; INSTALL_PREFIX=/usr/local; fi
  - ./configure --with-tcl=$TCL_PREFIX --prefix=$INSTALL_PREFIX
  - make
  - sudo make install
